version: 2
updates:
  # Enable version checks and updates for Node.js dependencies.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    cooldown:
      semver-major-days: 10
      semver-minor-days: 5
      semver-patch-days: 2
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    allow:
      - dependency-type: "all"
    ignore: []
  # Enable version updates for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "03:00"
    cooldown:
      semver-major-days: 10
      semver-minor-days: 5
      semver-patch-days: 2
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    allow:
      - dependency-type: "all"
    ignore: []
